# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245898a68f9a5a93c8734f7326367f7d87e1056a2a0e26f1af88fda1fba7f704f9ddc8e1247011080aaed5ac375cba34c40795dac05596087a1944fe29d6f47f

test:
  secret_key_base: c68ec753fa7ce25abbe4044b11f4cfdce6ea7b6c4fe5cd4ce9f84a5ee59241bb703ac3dc848635216f82a360d59f438544971f2a09b127c33393dccc46b3adc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
